version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    command: >
      sh -c "uvicorn src.main:app --reload --port=8000 --host=0.0.0.0"
